---
- name: 'Installing pkgs to manage {{ ansible_pkg_mgr }} repos'
  package:
    name: ca-certificates, curl, gnupg2, software-properties-common 
    state: present 
  tags: pkg_mgr_prereqs

- name: 'Adding GlusterFs Repo' 
  apt_repository:
    repo: "ppa:gluster/glusterfs-{{ glusterfs_version }}"
    state: present
    update_cache: yes
  tags: add_gluster_repo

- name: 'Installing GlusterFS Server, Client pkgs'
  package:
    name: glusterfs-server, glusterfs-client
    state: present
  tags: install_glusterfs_pgs

- name: 'Enable Start glusterd service'
  service:
    name: glusterd
    state: started
    enabled: yes
  tags: enable_glusterd_svc 
